# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

artist_1 = Artist.create(name: "Robert Glasper")
artist_2 = Artist.create(name: "Esperanza Spalding")
artist_3 = Artist.create(name: "Chris Dave")
artist_4 = Artist.create(name: "Charles Mingus")
artist_5 = Artist.create(name: "Bari S")
artist_6 = Artist.create(name: "Pharoah Sanders")
artist_7 = Artist.create(name: "Takuya Kuroda")
artist_8 = Artist.create(name: "Oscar Jerome")
artist_9 = Artist.create(name: "Erykah Badu")
artist_10 = Artist.create(name: "Gunhild Carling")
artist_11 = Artist.create(name: "Derrick Hodge")
artist_12 = Artist.create(name: "Jordan Rakei")
artist_13 = Artist.create(name: "R+R=NOW")
artist_14 = Artist.create(name: "Quelle Chris and Chris Keys")
artist_15 = Artist.create(name: "Morehead State college jazz group")
artist_16 = Artist.create(name: "Kojey Radical")
artist_17 = Artist.create(name: "Dinner Party")
artist_18 = Artist.create(name: "Kendrick Lamar")
artist_19 = Artist.create(name: "Thundercat")
artist_20 = Artist.create(name: "Yussef Dayes X Alfa Mist")
artist_21 = Artist.create(name: "Ahmad Jamal")
artist_22 = Artist.create(name: "Wayne Shorter")
artist_23 = Artist.create(name: "Marquis Hill Blacktet")
artist_24 = Artist.create(name: "Bobby McFerrin and Chick Corea")
artist_25 = Artist.create(name: "Minnie Riperton")
artist_26 = Artist.create(name: "Alice Coltrane")
artist_27 = Artist.create(name: "Duke Ellington and John Coltrane")
artist_28 = Artist.create(name: "John Coltrane")
artist_29 = Artist.create(name: "Miles Davis")
artist_30 = Artist.create(name: "Bilal")
artist_31 = Artist.create(name: "Nina Simone")
artist_32 = Artist.create(name: "Robert Glasper, Metropole Orkest and Bilal")

video_1 = JazzVideo.create(vid: "8yQE8v-5GTU", artist_id: 1)
video_2 = JazzVideo.create(vid: "2aRC3YY3svs", artist_id: 2)
video_3 = JazzVideo.create(vid: "NGv366y_UjQ", artist_id: 3)
video_4 = JazzVideo.create(vid: "__OSyznVDOY", artist_id: 4)
video_5 = JazzVideo.create(vid: "sR5qJy-wsRE", artist_id: 5)
video_6 = JazzVideo.create(vid: "QZ6lB7FKxi8", artist_id: 6)
video_7 = JazzVideo.create(vid: "uww2R-Cql1o", artist_id: 7)
video_8 = JazzVideo.create(vid: "msaDkCvnRM4", artist_id: 8)
video_9 = JazzVideo.create(vid: "4cfmEgpOOZk", artist_id: 9)
video_10 = JazzVideo.create(vid: "NZCaf9r-Djc", artist_id: 10)
video_11 = JazzVideo.create(vid: "NgEqzwqMKyw", artist_id: 11)
video_12 = JazzVideo.create(vid: "JtBmUxz4GsM", artist_id: 12)
video_13 = JazzVideo.create(vid: "hDa9_LJoSTY", artist_id: 13)
video_14 = JazzVideo.create(vid: "zu6APmk9X7Y", artist_id: 14)
video_15 = JazzVideo.create(vid: "cExdNEWVFsI", artist_id: 15)
video_16 = JazzVideo.create(vid: "BISwARqP8L0", artist_id: 16)
video_17 = JazzVideo.create(vid: "nF9ijAzW_Q0", artist_id: 17)
video_18 = JazzVideo.create(vid: "drV0QatqbRU", artist_id: 18)
video_19 = JazzVideo.create(vid: "GNCd_ERZvZM", artist_id: 19)
video_20 = JazzVideo.create(vid: "NwVtIPeYIeQ", artist_id: 20)
video_21 = JazzVideo.create(vid: "j1DithiAmko", artist_id: 21)
video_22 = JazzVideo.create(vid: "2iZ7id-lxXo", artist_id: 22)
video_23 = JazzVideo.create(vid: "I0xaO3JLwDU", artist_id: 23)
video_24 = JazzVideo.create(vid: "_o2RS8WfcbY", artist_id: 24)
video_25 = JazzVideo.create(vid: "UVniMFJYY1o", artist_id: 25)
video_26 = JazzVideo.create(vid: "f5EoZsaiS9U", artist_id: 26)
video_27 = JazzVideo.create(vid: "sCQfTNOC5aE", artist_id: 27)
video_28 = JazzVideo.create(vid: "pQ3_nlpnfuA", artist_id: 28)
video_29 = JazzVideo.create(vid: "eE_D6Kve1SM", artist_id: 29)
video_30 = JazzVideo.create(vid: "9QupZbIQkQ0", artist_id: 30)
video_31 = JazzVideo.create(vid: "Mf_5l1yTKNY", artist_id: 31)
video_32 = JazzVideo.create(vid: "0GAsHvknO1k", artist_id: 32)